// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backup} from '../models';
import {config} from '../models';

export function AcceptEULA():Promise<void>;

export function CancelBackup():Promise<string>;

export function DeclineEULA():Promise<void>;

export function GetAvailableDrives():Promise<Array<string>>;

export function GetBackupStatus():Promise<backup.BackupStatus>;

export function GetConfig():Promise<config.Config>;

export function GetDiskInfo(arg1:string):Promise<Record<string, any>>;

export function GetEULAText():Promise<string>;

export function GetMachineID():Promise<string>;

export function GetMountedSnapshot():Promise<string>;

export function GetNextBackup():Promise<string>;

export function GetSnapshotFiles(arg1:string,arg2:string):Promise<Array<backup.FileInfo>>;

export function GetSnapshots():Promise<Array<backup.SnapshotMeta>>;

export function IsAutoStartEnabled():Promise<boolean>;

export function IsEULAAccepted():Promise<boolean>;

export function MountSnapshot(arg1:string):Promise<string>;

export function PurgeSourceDirBackups(arg1:string):Promise<void>;

export function RestoreFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RunBackupNow():Promise<void>;

export function SaveConfig(arg1:Array<string>,arg2:string,arg3:string,arg4:string,arg5:config.SMBShareConfig,arg6:config.RetentionPolicy,arg7:boolean,arg8:Array<string>):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectTargetDirectory():Promise<string>;

export function TestSMBConnection(arg1:config.SMBShareConfig):Promise<void>;

export function UnmountSnapshot():Promise<void>;
