// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptEULA() {
  return window['go']['main']['App']['AcceptEULA']();
}

export function CancelBackup() {
  return window['go']['main']['App']['CancelBackup']();
}

export function DeclineEULA() {
  return window['go']['main']['App']['DeclineEULA']();
}

export function GetAvailableDrives() {
  return window['go']['main']['App']['GetAvailableDrives']();
}

export function GetBackupStatus() {
  return window['go']['main']['App']['GetBackupStatus']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDiskInfo(arg1) {
  return window['go']['main']['App']['GetDiskInfo'](arg1);
}

export function GetEULAText() {
  return window['go']['main']['App']['GetEULAText']();
}

export function GetMachineID() {
  return window['go']['main']['App']['GetMachineID']();
}

export function GetMountedSnapshot() {
  return window['go']['main']['App']['GetMountedSnapshot']();
}

export function GetNextBackup() {
  return window['go']['main']['App']['GetNextBackup']();
}

export function GetSnapshotFiles(arg1, arg2) {
  return window['go']['main']['App']['GetSnapshotFiles'](arg1, arg2);
}

export function GetSnapshots() {
  return window['go']['main']['App']['GetSnapshots']();
}

export function IsAutoStartEnabled() {
  return window['go']['main']['App']['IsAutoStartEnabled']();
}

export function IsEULAAccepted() {
  return window['go']['main']['App']['IsEULAAccepted']();
}

export function MountSnapshot(arg1) {
  return window['go']['main']['App']['MountSnapshot'](arg1);
}

export function PurgeSourceDirBackups(arg1) {
  return window['go']['main']['App']['PurgeSourceDirBackups'](arg1);
}

export function RestoreFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['RestoreFile'](arg1, arg2, arg3);
}

export function RunBackupNow() {
  return window['go']['main']['App']['RunBackupNow']();
}

export function SaveConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectTargetDirectory() {
  return window['go']['main']['App']['SelectTargetDirectory']();
}

export function TestSMBConnection(arg1) {
  return window['go']['main']['App']['TestSMBConnection'](arg1);
}

export function UnmountSnapshot() {
  return window['go']['main']['App']['UnmountSnapshot']();
}
